### ISSUE TITLE
Filter timestamps between times from specific time zone

### ISSUE THREAD

**Issue by MislavSag** [eddelbuettel/nanotime#103]
I am experimenting with nanotime package (try to replace not very efficient lubridate package). My goal is:
1. change timezone form UTC to NY.
2. Keep only rows where time is between 09:30 and 16:00.
3. count number of seconds from midnight for every row.

I don't know how to filter timestamps between 09:30 for specific timezone. Her is my try:
```
        library(nanotime)
        library(data.table)
        
        # sample data
        from <- as.nanotime("2018-01-14T00:00:00+00:00")
        to   <- as.nanotime("2018-01-30T00:00:00+00:00")
        seq_nano <- seq(from, to, by = nanoduration(hours = 0, minutes = 1, seconds = 0, nanoseconds = 0), tz="America/New_York")
        dt <- data.table(date = seq_nano, x = runif(length(seq_nano)))
        
        # change timezone
        dt[, date := format(date, tz = "America/New_York")]
        
        # keep dt between 09:30 and 16:00, my tries doesn't work because date is now character. when using psxcit I can use between from data.table
        dt[format(date, format = "%H:%M:%S") %in% c(as.nanoduration("09:30:00"), as.nanoduration("16:00:00"))]
        dt[format(date, format = "%H:%M:%S") %between% c("09:30:00", as.nanoduration("16:00:00"))]

        # count number of seconds from midnight
        dt[, `:=`(DateTime = (hour(date) * 3600 + minute(date) * 60 + second(date)) * 1000,
                  Open = open * 10000,
                  High = high * 10000,
                  Low = low * 10000,
                  Close = close * 10000,
                  Volume = volume)]
```

**Comment by eddelbuettel** [comment]
I cannot quite put my finger on it but I have the feeling your are doing this wrong.   Exchange time is often UTC for a reason, so maybe you are better off converting _your desired boundaries_ from local cutoff time (say: NY 9:30) to UTC and check that.  

`nanotime` has no strong opinion about timezone, and just compares. If you read the help page carefully you see that that

> \item{tz}{character specifying a timezone which is required for
> \code{as.POSIXct}, \code{as.POSIXlt} and can be specified for
> \code{as.nanotime}, \code{format} and \code{print}; it can
> also be set via \code{options("nanotimeTz")} and uses
> \sQuote{UTC} as a default and fallback}

is uses timezone just for converting from/to human display format. Internally everything is likely UTC (but I don't recall if we made this a hard constraint or).  

Lastly, `nanotime` relies on package `RcppCCTZ` for the actual parsing and formatting, and I added a few timezone utilties to `RcppCCTZ`.  If you really must you may try those.  My instinct is that are likely best off to remain in `data.table` (using `IDateTime` at `POSIXct` granularity) and to crawl StackOverflow (and alike) for efficient `data.table` solutions.

**Comment by MislavSag** [comment]
I will follow your advice and use only UTC tz. Then I can use both DT/nanotime and DT/POSIXct approaches.

Thanks.
