### ISSUE TITLE
Add/subtract methods for nanoduration/difftime durations

### ISSUE THREAD

**Issue by trevorld** [eddelbuettel/nanotime#107]
* As a follow-up to #106 I could do a PR to add S4 "+"/"-" methods to add difftime and nanoduration durations together

**Comment by eddelbuettel** [comment]
See #108, and next time please pool issues that are effectively identical (+/- methods for nano{time,duration} objects) in one if you can.   Maybe consider a single PR too for both #107 and #108.  Thank you for your consideration, and thanks for offering to do this.
