### ISSUE TITLE
Add 'as.nanoduration.Duration()'

### ISSUE THREAD

**Issue by trevorld** [eddelbuettel/nanotime#109]
Currently downstream in my experimental [{datetimeoffset}](https://github.com/trevorld/r-datetimeoffset) package I implement and use an `as.nanoduration()` method for `{lubridate}` durations:

```r
setMethod("as.nanoduration", "Duration", function(x) {
    x <- as.numeric(x, "seconds")
    s <- as.integer(x) # seconds
    n <- as.integer(1e9 * (x - s)) # nanoseconds
    nanoduration(seconds = s, nanoseconds = n)
})
```

I'd be happy to do a PR to contribute it upstream to `{nanotime}` but will not do so unless I get the go ahead since I'd either need to add `{lubridate}` to the package `DESCRIPTION` `Suggests` field assuming we can dynamically add S4 methods `.onLoad()` (like we can with S3 methods) or to `Enhances` (if we can't do so).

**Comment by eddelbuettel** [comment]
I personally get by just fine without `lubridate` and (at least right now) have no immediate plans to add support to `nanotime`.  What do you think @lsilvest ?

**Comment by lsilvest** [comment]
Yes, I agree, I don't think we want to reference `lubridate`. I think these two packages are rather either/or than complementary.

**Comment by lsilvest** [comment]
Btw, @trevorld, I had a quick look at your `datetimeoffset` project, and just wanted to comment about an idea in `nanotime` which is deliberate. We specifically choose not to associate a timezone with `nanotime`. At most during some operations like printout we fetch (if not present in the argument) a default time zone in which to print, but we never perform any transformation in which the timezone is relevant without requesting it explicitly (for instance plus/minus ops with `nanoperiods`). This is based on the experience that storing offset information with time is incredibly error prone with code that has unintended mixed offsets or that assumes a specific offset. Having the timezone as a parameter of the transformation forces the code to explicitly fetch the offset and that has proven to be a safer alternative.

**Comment by trevorld** [comment]
* Okay, I'll consider this "out of scope".
* @lsilvest thanks for the quick look.  The motivating use case for `{datetimeoffset}` is as a helper package for [{xmpdf}](https://github.com/trevorld/r-xmpdf) which is a package I'm writing for editing PDF metadata in R.  I need a datetime aware object that can **losslessy** handle mixed-precision local datetimes with known/unknown UTC offsets and **unknown** time zones.  I agree that if you have "full precision" datetimes with known time zones what you are doing seems easier/safer.

**Comment by lsilvest** [comment]
Yes, there are always use cases in which one solution ends up better than another.
