### ISSUE TITLE
format.nanotime: attribute 'tzone' and parameters 'format' and 'tz'

### ISSUE THREAD

**Issue by lsilvest** [eddelbuettel/nanotime#11]
Having format.nanotime behave like format.POSIXct would make it easier to replace POSIXct by nanotime. One specific example is for the 'xts' package.

**Comment by eddelbuettel** [comment]
Maybe. But also a lot more headaches for me.  So far I am happy with UTC as default.

**Comment by eddelbuettel** [comment]
Did you see that you can set format and tz as options?

```r
R> n <- nanotime("2120-01-01T00:00:59.987654321+00:00")
R> format(n)
[1] "2120-01-01T00:00:59.987654321+00:00"
R> options("nanotimeTz"="America/New_York")
R> format(n)
[1] "2119-12-31T19:00:59.987654321-05:00"
R> 
```

As for a `tzone` attribute:  maybe once nanotime gets into xts?

**Comment by lsilvest** [comment]
Yes, I did see these options. But wouldn't it be less confusing and more flexible if the time zone handling were as in _POSIXct_, i.e. _tzone_ attribute and a pull of the system time zone if it is missing? Like that the user doesn't need to bother with another global setting and things work in a more expected way.

The point of the _tzone_ attribute is two-fold. First it allows a specific array/vector of _nanotime_ to be displayed in a specified time zone for that array/vector (like _POSIXct_). The second one is the integration with _xts_. There's very little that needs to be modified if _nanotime_ behaves like _POSIXct_.

It's also really easy to implement; here is the format.POSIXct code:

~~~ R
format.POSIXct <- function(x, format = "", tz = "", usetz = FALSE, ...)
{
    if(!inherits(x, "POSIXct")) stop("wrong class")
    if(missing(tz) && !is.null(tzone <- attr(x, "tzone"))) tz <- tzone
    structure(format.POSIXlt(as.POSIXlt(x, tz), format, usetz, ...),
              names = names(x))
}
~~~

Then in _format.POSIXlt_ a C function is called that gets the system time zone, but this could be easily got at R level too of course.

And last, if the default format for the time zone were "%Z", the display would be more like POSIXct, again something users might prefer, but it's a minor point of course and there might be other reasons to prefer the current default with "%Ez".

**Comment by eddelbuettel** [comment]
Well nanotime isn't POSIXct.  As you write in your docs, POSIXct falls a little short on resolution, So for the time being I am quite ok with the formatted output looking different.

The package is very, very young.  We're still fixing some key functionality (such as the two rounding issues you identified -- thanks again for that!) and I am sure we'll get to the right feature mix.   But I don't think this is super-urgent for now.   (And again, you could just _one_ set your prefered format and tz in your Rprofile.site or .Rprofile and would already be reflected...)

**Comment by lsilvest** [comment]
Agreed it's not urgent. I just wanted to precise that I think the difference in output format i.e. with the "T" seems actually good, because, as you say, nanotime isn't POSIXct, and the type difference is clearer with a different default printout. I was just talking about the time zone marker "%Z" vs. "%Ez", as I think many users will find "CET", "BST", "EST", etc. less confusing than a numeric offset, but maybe that's just me.

So this issue can be closed and maybe there will be other feedback. I also think the 'tzone' discussion will come back with the 'xts' integration. By the way, do you think it's worth starting that discussion now with the 'xts' maintainer?

**Comment by eddelbuettel** [comment]
I think we're on the page.   

And just to be explicit, if you want `%Z` you can have it now too:

```r
R> options("nanotimeFormat"="%Y-%m-%dT%H:%M:%E9S %Z")
R> format(n)
[1] "2119-12-31T19:00:59.987654321 EST"
R> 
```

(and I just found one last instance of  `%E*S` which needs to `%E9S`....)

**Comment by lsilvest** [comment]
Yes, I got that, the format option for nanotime is great. Thanks!

**Comment by lsilvest** [comment]
I made some concurrent changes to xts and nanotime in forked repositories (https://github.com/lsilvest/nanotime and https://github.com/lsilvest/xts). 

I've tested index.xts, coredata.xts, cbind.xts, rbind.xts, period.sum, and a few other functions. Much more needs to be tested. Did notice that plot.xts doesn't work.

**Comment by eddelbuettel** [comment]
I glanced at the (short) diff to nanotime. That won't fly as is.  New function parameters must go to the end, you can't inject in the middle. You can (should !) set a default for getOption() as I do.

I think all that can still be done with the global `options("nanotimeTz")`. Am I missing something?

**Comment by lsilvest** [comment]
OK, makes sense, will put it at the end. 

The reason there is no default is that if there is no option, then it fetches the system time zone, which, if not set, then defaults to UTC (that is also the behavior of POSIXct).

The reason for the tzone attribute (both for xts and in POSIXct) is so that different POSIXct arrays and different xts time series can have different time zones attributes. That's pretty essential if you have data generated from all over the world. A global option is much more limiting.

Lastly, when it is possible for nanotime to be similar to POSIXct in its interface and behavior it makes it much easier to replace in any package that uses POSIXct, from a coding standpoint, but also because users will probably expect similar behavior. Case in point is xts.

**Comment by eddelbuettel** [comment]
I could live with it at the end, being unset, and `if (missing(...))` we go switch to
 `getOption("nanotimeTz", default="UTC")`.   The TZ env var is sometimes unset (see micropackage gettz of mine) though R now tries harder to ensure it is there.

**Comment by lsilvest** [comment]
Do you mean like this or do you want `tz` after the ellipsis (I don't know your intentions for the other arguments including the ellipsis)?

~~~ R
format.nanotime <- function(x,
                            justify="right",
                            digits=NULL,
                            na.encode=FALSE,
                            trim=TRUE,
                            tz="",
                            ...) {
    fmt <- getOption("nanotimeFormat", default="%Y-%m-%dT%H:%M:%E9S%Ez")
    if (missing(tz) && !is.null(tzone <- attr(x, "tzone")))
      tz <- tzone
    else
      tz <- getOption("nanotimeTz", default="UTC")
    bigint <- as.integer64(x)
    secs  <- as.integer64(bigint / as.integer64(1000000000))
    nanos <- bigint - secs * as.integer64(1000000000)
    RcppCCTZ::formatDouble(as.double(secs), as.double(nanos), fmt=fmt, tgttzstr=tz)
}
~~~

**Comment by eddelbuettel** [comment]
Yes, that is better.  

As I recall the semantic of `missing()` are such that it has to come first so move it above `fmt <- ...`.

The rest could work.

**Comment by lsilvest** [comment]
OK, thanks.

**Comment by vspinu** [comment]
A couple of extra cents on this.

Global options for time related stuff cause endless compatibility errors. Core R's reliance on locale TZ  is a nightmare. There should be at least a big warning somewhere that setting those options is bad idea. 

Currently tz and fmt are set inside the [character constructor](https://github.com/eddelbuettel/nanotime/blob/master/R/nanotime.R#L104). This is not good for programatic usage. So not just `format` but all constructors should have `tz` and `fmt`  arguments whenever appropriate. 

There is also an issue of comparison to strings (not supported yet, but would be nice). If not taken care global format option will interfere with that. 

```R
> nanotime("1970-01-01T00:00:00.000000001+00:00") >  "1970-01-01T00:00:00"
[1] NA
> as.POSIXct("1970-01-01 00:00:10") >  "1970-01-01T00:00:00"
[1] TRUE
```

@lsilvest, using `missing()` inside a function makes it difficult to work programaticaly with. Better to check for NULL or "" directly.

**Comment by eddelbuettel** [comment]
I think I like the current style better, and I am also not sure I follow what you are saying.   Why would this be "difficult to work with programmatically" ?

**Comment by vspinu** [comment]
I was making a general comment that using missing is bad style because the code which calls your function needs to supply "missing" to get the default behavior.   Last time I checked there was no easy way to supply "missing".

In [current implementation](https://github.com/eddelbuettel/nanotime/blob/master/R/nanotime.R#L160-L173) if external code calls `format(nt, tz="")` the `if (missing(tz)){` block is not called and this is probably not what you want, or do you?

**Comment by eddelbuettel** [comment]
I don't understand.  To me these two are equivalent:

```r
R> a <- function(arg=42) arg
R> b <- function(arg) { if(missing(arg)) arg <- 42; arg }
```

and there are cases where I like the interface of `b` better.   This is one such case.

**Comment by lsilvest** [comment]
I think it's correct that `tz` and `format` should be parameters in the constructors where appropriate.

Automatic comparison to strings is in my opinion always going to be too difficult, precisely because of formatting. As you pointed out, that's the same issue with `POSIXct` (and additionally `POSIXct` will silently drop a time zone specification in a `character`). I think there's a trade-off between the flexibility/comfort of working and the reliability/portability. 

@vspinu is saying that if you call `format.nanotime` explicitly setting `tz=""`, the time zone is not set by `format.nanotime`. I suppose a user would expect explicitly setting `tz=""` to behave as if he hadn't set it at all, so I think it's a valid point.

**Comment by eddelbuettel** [comment]
As for 

> In current implementation if external code calls format(nt, tz="") the if (missing(tz)){ block is not called and this is probably not what you want, or do you?

that seems to be a bug indeed.  Should be `if (tz=="")`.

**Comment by eddelbuettel** [comment]
Ok, colour me now-convinced.  Would one of you have time to send a PR?

**Comment by lsilvest** [comment]
Yes, will send a PR.

Additionally, I feel a `nanotime`/`character` comparison should probably return an error rather than NA...

**Comment by vspinu** [comment]
> and there are cases where I like the interface of b better. 

Your two examples worn't be equivalent anymore if you do something more complicated than `a <- 43` in the missing block.  IMO, `missing` should be banned and imprisoned.  Besides being awkward in programs it almost always creates a tri-logic conditionals difficult to reason about.

> As you pointed out, that's the same issue with POSIXct (and additionally POSIXct will silently drop a time zone specification in a character).

**Comment by vspinu** [comment]
> As you pointed out, that's the same issue with POSIXct (and additionally POSIXct will silently drop a time zone specification in a character).

It's not that difficult to fix actually. lubridate fixes the tz issue in character comparison. POSIXct parsing doesn't deal with tzone because they don't have proper tools. Now that we have cctz it's much easier to handle.

**Comment by eddelbuettel** [comment]
I like `missing`.

**Comment by lsilvest** [comment]
I changed just the `missing` checks in baede393ced6f78d2235a1ad206a29743ccd60e5.

@eddelbuettel: I didn't understand if you agree with adding `format` and `tz` in the `nanotime` `character` constructor (and then logically `format` in `format.nanotime` too) or if your "convinced" only referred to the usage of `missing`?

**Comment by eddelbuettel** [comment]
Sorry.  What I was trying to say was that I like not to have to repeat arguments (to functions) over and over, particularly when they are in fact constant.   So in that sense I made the interface to `format.nanotime()` a little more narrow and had TZ automatically discovered if possible.  Now, I guess `format.nanotime()` needs to conform to the standard of other `format.*` functions particularly to those also doing time-related work.  So the comparison with `format.POSIXct` was apt.  And I have come around to changing that interface.

But I still like values being automatically setable.  So in that maybe   `tz=.someInternalGetter()` makes sense where we could either just rely on TZ or use `nanotimeTz` or use both.   

Does that sound reasonable?

**Comment by lsilvest** [comment]
Sure, I'll propose a version with the parameter changes then, keeping the way it currently works when unspecified (i.e. using `nanotimeFormat` and `nanotimeTz`).

**Comment by eddelbuettel** [comment]
PR #22 took care of this, so closing now.
