### ISSUE TITLE
'as.nanotime(NA_character_)' throws an ERROR

### ISSUE THREAD

**Issue by trevorld** [eddelbuettel/nanotime#112]
I observe that `as.nanotime()` returns an `NA` value for `NA_integer_` but throws an ERROR for `NA_character_`.  One may possibly expect that `as.nanotime(NA_character_)` should also return an `NA` value as well...

```r
library("nanotime")
as.nanotime(NA_integer_)
```
```r
<NA>
```
```r
as.nanotime(NA_character_)
```
```r
Error in RcppCCTZ::parseDouble(x, fmt = format, tzstr = tz) : 
  Parse error on NA
```

**Comment by eddelbuettel** [comment]
That's actually (from the `traceback()`) happening one level down in `RcppCCTZ` and its `parseDatetime()`:

> parseDatetime(formatDatetime(now + 0:4))
[1] "2022-11-03 20:25:18 UTC" "2022-11-03 20:25:19 UTC" "2022-11-03 20:25:20 UTC" "2022-11-03 20:25:21 UTC" "2022-11-03 20:25:22 UTC"
> parseDatetime(c(formatDatetime(now + 0:2), NA_character_, formatDatetime(now + 3:4)))
Error: Parse error on NA
>

**Comment by eddelbuettel** [comment]
I'll fix it there.  `nanotime` should inherit the improvement once an updated `RcppCCTZ` gets to CRAN in a day or two or three.

```r
> library(RcppCCTZ)
> now <- Sys.time(); parseDatetime(c(formatDatetime(now + 0:2), NA_character_, formatDatetime(now + 3:4)))
[1] "2022-11-03 20:37:36.24320 UTC" "2022-11-03 20:37:37.24320 UTC"
[3] "2022-11-03 20:37:38.24320 UTC" NA                             
[5] "2022-11-03 20:37:39.24320 UTC" "2022-11-03 20:37:40.24320 UTC"
> 
```

**Comment by eddelbuettel** [comment]
Actually needed a fix in two places.  Seems good now:

```r
> library(nanotime)
> library(RcppCCTZ)
> now <- Sys.time()
> as.nanotime(c(formatDatetime(now + 0:2), NA_character_, formatDatetime(now + 3:4)))
[1] 2022-11-03T21:07:50.168427+00:00 2022-11-03T21:07:51.168427+00:00
[3] 2022-11-03T21:07:52.168427+00:00 <NA>                            
[5] 2022-11-03T21:07:53.168427+00:00 2022-11-03T21:07:54.168427+00:00
> 
```

Feel free to fetch RcppCCTZ from its GH repo in a moment once I commit the second change :)

**Comment by trevorld** [comment]
* Thanks!
* I installed the development version of `{RccpCCTZ}` using `remotes::install_github()` and now my `as.nanotime()` method seems to be correctly handling missing datetimes.

**Comment by eddelbuettel** [comment]
The updated `RcppCCTZ` package is now on CRAN.
