### ISSUE TITLE
as.Date does not handle the case where tz is a vector

### ISSUE THREAD

**Issue by lsilvest** [eddelbuettel/nanotime#118]
We handle `tz` as a vector it correctly in the extract functions (`nano_month`, etc.), but in our `as.Date` we convert first to `POSIXct` and then call the base `as.Date` . So the idea here is to use our own functions instead of relying on `POSIXct`.

**Comment by eddelbuettel** [comment]
Could do.  Do you have a use case for that?

**Comment by lsilvest** [comment]
Yes, I recently had a set of observations over a couple of months with UTC times, all with different geographical locations and needed to group the observations by day. I converted the geographical locations to timezones, but couldn't directly use `nanotime`'s `as.Date` as it doesn't accept a vector of timezones. Got out of trouble with `nano_month`, etc., but we could easily fix our `as.Date` to handle that out of the box.

**Comment by eddelbuettel** [comment]
Do you have a clever idea for how to do 'maybe-vectorization' ?  Or maybe we already di elsewhere?

**Comment by lsilvest** [comment]
Fortunately, we've already got some vectorization for this at C level, so it turns out to be fairly straightforward. See if this new code seems OK to you.

**Comment by eddelbuettel** [comment]
Really nice.  I had one gut-instinct idea now but not strong feeling either way.  With/without automagic tz works for me.
