### ISSUE TITLE
demo/ggplot2Example does not work

### ISSUE THREAD

**Issue by travis-leith** [eddelbuettel/nanotime#131]
At least not with the latest version of ggplot2 (3.5.1)

Even the test in the demo fails

```R
## create `data.table` with `idx` of type `nanotime`:
  idx <- nanotime(1) + 1e9*(1:100)
  dt <- data.table(idx=idx, a=1:100, b=11:110)
  
  ## nanotime on the x-axis:
  ggplot(dt, aes(x=idx, y=b)) +
    geom_line()
```

fails with

`Error: Invalid input: nanotime_trans works with objects of class nanotime only`

The failure happens at this check

```R
 if (!inherits(x, "nanotime")) {
        stop("Invalid input: nanotime_trans works with objects of class ",
             "nanotime only", call. = FALSE)
      }
```

**Comment by travis-leith** [comment]
Is it worth making this functionality a core part of the package, and including official tests to prevent regression?

**Comment by travis-leith** [comment]
I can get this to work if I remove the type check and also remove anything to do with time zones.

**Comment by eddelbuettel** [comment]
Ack.  `scales` and other things like preferred / default transformation names appear to have changed since this was written as  `ggplot2` tends to change for better or (here) worse.

This may just need to be withdrawn.

**Comment by eddelbuettel** [comment]
@lsilvest My memory is foggy but we seem to have taken this from your repo at [lsilvest/nanotime_ggplot](https://github.com/lsilvest/nanotime_ggplot).  

Have you by chance revisited 'scales' for ggplot2 for nanotime?

**Comment by eddelbuettel** [comment]
There is a micro-error in the demo file:

```diff
modified   demo/ggplot2Example.R
@@ -12,7 +12,7 @@ if (requireNamespace("ggplot2", quietly=TRUE) &&
 
     nanotime_format <- function(format = getOption("nanotimeFormat", default="%Y-%m-%dT%H:%M:%EXS%Ez"),
                                 tz     = getOption("nanotimeTz", default="UTC")) {
-        function(x) format(x, format, tz=tz)
+        function(x) format(x, format, tz)
     }
 
```

but even with that fixed, and running under Ubuntu 20.04 "focal" as a test (to get an older ggplot2) I get an error:

```r
Error in validate_guide(guide) : Unknown guide
```

I think it may be best to just quietly retire this demo file.  One _can_ plot with nanotime by running as.POSIXct() over the column first.

**Comment by travis-leith** [comment]
On one hand I think retiring it would be a shame, but on the other hand, this package isn't really about supporting visualisations from other packages so makes sense to retire.

**Comment by lsilvest** [comment]
Yes, I imagine there's been some changes in `ggplot2`... Before we decide to retire it, I'll take a stab at it and see if we can fix this.

**Comment by eddelbuettel** [comment]
We are coming up to a new CRAN release and I plan to skip shipping the example file there.  It needs a bigger update, and maybe these days there are other ggplot2 helper packages for scale manipulation that we can lean on.  Another time.
