### ISSUE TITLE
Flagging compiler issue

### ISSUE THREAD

**Issue by MichaelChirico** [eddelbuettel/nanotime#134]
Hey Dirk! Wanted to flag that this form of declaration for `Rcomplex` is throwing compiler errors for us:

https://github.com/eddelbuettel/nanotime/blob/48d48a7b42e3bef173b5312b5fbb3c9b1776b40f/src/period.cpp#L188

Example:

```
nanotime/src/period.cpp:189:23: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
  189 |     res[i] = Rcomplex{pu.dbl2.d1, pu.dbl2.d2 };
      |                       ^~~~~~~~~~~~~~~~~~~~~~
      |                       {                     }
```

R 4.1.3, no issue, R 4.4.1, issue. I am pretty puzzled why we're seeing it but not you or CRAN.

We fixed it with `-DR_LEGACY_RCOMPLEX` per the <R_ext/Complex.h> header:

https://github.com/r-devel/r-svn/blob/fc865847f6f7110f06cb361027a7007f670c6733/src/include/R_ext/Complex.h#L33

Another fix is to do what the warning suggests and add an extra layer of `{}`, but that requires some `#if R_VERSION` mess I found more onerous.

This is very likely where the issue arose:

https://github.com/r-devel/r-svn/commit/862f9f816ff3ff3cb3f851603f19e99f60a98475

Which would have arrived in R 4.3.0:

https://github.com/wch/r-source/blob/tags/R-4-3-0/src/include/R_ext/Complex.h

Anyway, not sure if there's anything to do here (could be something idiosyncratic on our end), but sharing in case this does start showing up at some point. Feel free to close.

**Comment by eddelbuettel** [comment]
Hey Michael you state 'compiler issue' yet never share which compiler you use. A small reproducible example using a Docker container would go a long way.

"Usually" these types of warnings come from the direction of a well-known old European university where one dedicated R developer tends to run early clang or gcc versions.  Now, at CRAN [we are clearly fine](https://cloud.r-project.org/web/checks/check_results_nanotime.html).

Off-hand, I can see how brace initialization may throw the compiler off as Rcomplex is not really a plain old data structure, and I suspect that this ultimetely may be caused by LTO -- but that is just a hunch.

In the meantime we can always add the define for `-DR_LEGACY_RCOMPLEX` to the package or user compiler flags as you hint.

**Comment by MichaelChirico** [comment]
This is coming from our internal toolchain (something like a fork of `clang`), hence no reproduction.

I will close since I think we agree on the diagnosis + fix, _should this issue actually start showing up with open-source compilers_.

From here, it's also possible I've misconfigured the package 🙃

https://stackoverflow.com/questions/31555584/why-is-clang-warning-suggest-braces-around-initialization-of-subobject-wmis

Thanks for lending your ear!

**Comment by kiwiwarmnfuzzy** [comment]
Here is the godbolt repro: https://godbolt.org/z/jK6TfrM91, with Clang trunk and the `-Wmissing-braces` warning enabled.

**Comment by eddelbuettel** [comment]
Sorry but a non-reproducible issue (in the "does not show up at CRAN" sense) is not helping anyone.  But all means, leave it open if you feel that helps; the only ones who can work on are you two.

**Comment by MichaelChirico** [comment]
@kiwiwarmnfuzzy's link shows the reproduction (NB: it doesn't appear on the mobile site). #135 has a fix.

**Comment by eddelbuettel** [comment]
Sorry, while gotbolt is a nice tool (and its namesake a Chicago-area aquaintance) that is not relevant. 

You have a need to accommodate one (newer) compiler. Please do so with minimal shrapnel.  Macros are a code smell.

**Comment by eddelbuettel** [comment]
A much simpler fix might be to just slap a second level of curly braces around:

```diff
modified   src/period.cpp
@@ -185,7 +185,7 @@ Rcpp::ComplexVector period_from_string_impl(Rcpp::CharacterVector str) {
   for (R_xlen_t i=0; i<str.size(); ++i) {
     period prd(Rcpp::as<std::string>(str[i]));
     period_union pu = { { prd.getMonths(), prd.getDays(), prd.getDuration().count() } };
-    res[i] = Rcomplex{pu.dbl2.d1, pu.dbl2.d2 };
+    res[i] = Rcomplex{ {pu.dbl2.d1, pu.dbl2.d2} };
   }
   if (str.hasAttribute("names")) {
     res.names() = str.names();

````

This works just fine here (Ubuntu 24.04, g++ 14):

```sh
using C++17
ccache g++-14  -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG  -I'/usr/local/lib/R/site-library/Rcpp/include' -I'/usr/local/lib/R/site-library/RcppCCTZ/include' -I'/usr/local/lib/R/site-library/RcppDate/include'    -I../inst/include -fpic  -O3 -Wall -pipe -pedantic -fdiagnostics-color=always -Wformat    -c period.cpp -o period.o
ccache g++-14 -std=gnu++17 -Wl,-S -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl,-z,relro -o nanotime.so RcppExports.o duration.o interval.o nanotime.o period.o rounding.o strnlen.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-nanotime/00new/nanotime/libs
```

and also via clang++ 18 (which made me change the few other spots).   So if you want to help I suggest maybe a simple inline function `makeComplex` which uses either the existing or the 'dual brace sets' approach depending maybe on the same #if use in the header.   Could you set that up and test it at your end?

**Comment by kiwiwarmnfuzzy** [comment]
> A much simpler fix might be to just slap a second level of curly braces around:

Oh well, but the second level of curly braces gets flagged by Clang trunk with `-Wmissing-braces` as extra, when using the `R_LEGACY_RCOMPLEX` definition: https://godbolt.org/z/6q4KTrMPv

<img width="1775" alt="Screenshot 2024-10-30 at 2 20 55 PM" src="https://github.com/user-attachments/assets/3952bac5-8d53-4c33-922a-2513469d492b">

**Comment by eddelbuettel** [comment]
Worked here with clang++ 18.  Anyway, I just wrapped it with an inline function:

```c++
inline Rcomplex makeComplex(double re, double im) {
#ifdef R_LEGACY_RCOMPLEX
    return Rcomplex{re, im};
#else
    // this makes clang++ 18 and later happier
    return Rcomplex{ {re, im} };
#endif
}
```

Are you saying that would not pass muster on your end?

**Comment by kiwiwarmnfuzzy** [comment]
I haven't checked if https://github.com/eddelbuettel/nanotime/issues/134#issuecomment-2448459585 works, but quite confident that i will. What I was trying to say in the previous comment is that just adding double braces without conditioning on the compiler directive causes compiler warning in some cases.

**Comment by eddelbuettel** [comment]
@kiwiwarmnfuzzy Sorry to be dense here (maybe it is the weather) but I still do not understand what you are saying.  It reads as if you are saying that the following would not compile?

```c++

#include <R_ext/Complex.h>
#include <iostream>

int main(int argc, char *argv[]) {
  Rcomplex v{ {1.1, 2.2} };
  std::cout << "V is " << v.r << " " << v.i << std::endl;
  return 0;
}
```

Works fine here (and you see where my default R sits on Ubuntu)

```sh
edd@rob:/tmp/r$ clang++-18 -o rcomplex_minimal rcomplex_minimal.cpp -Wall -I/usr/share/R/include 
edd@rob:/tmp/r$ ./rcomplex_minimal 
V is 1.1 2.2
edd@rob:/tmp/r$ 
```

**Comment by kiwiwarmnfuzzy** [comment]
What I was saying is that `R_LEGACY_RCOMPLEX` + `Rcomplex{{0.1, 0.1}}` (double braces) causes Clang warning "excess elements in scalar initializer" (https://godbolt.org/z/5sbrKdxej), without any warning flags.  Thus simply having double braces won't work for the case when `R_LEGACY_RCOMPLEX` is enabled (which should be rather uncommon), and therefore we will need a compiler directive, which is what https://github.com/eddelbuettel/nanotime/issues/134#issuecomment-2448459585 proposes and I _think_ will work when `R_LEGACY_RCOMPLEX` is enabled or disabled.

The double braces didn't result in compiler warning in your local installation probably because your local installation doesn't have the `R_LEGACY_RCOMPLEX` flag enabled.

**Comment by eddelbuettel** [comment]
Yup. Once you actually spell out all the conditions rather than leaving them unspoken it becomes clearer.  

And the macOS fail we just ran into in CI may also be related.  We may have to nail down where and when double braces is useful -- but you also seem to have sunk your teeth into an earlier common ("just add double braces") which was rendered moot by actual inline functions used by both Michael and myself.   So let's move on forward to making that inline function work.

**Comment by MichaelChirico** [comment]
Aside: cc @romainfrancois as maintainer of {Rcpp11}, which AFAICT is the only other R package using the `Rcomplex{` approach:

https://github.com/search?q=org%3Acran+%2FRcomplex%5Cs*%5C%7B%2F+-lang%3ARust+-repo%3Acran%2Fnanotime&type=code

{Rcpp} has very similar code, which uses a different approach for working with `Rcomplex` altogether:

https://github.com/RcppCore/Rcpp/blob/1761e1d64e7dd114150b40445b6e2ba1d30b98b2/inst/include/Rcpp/complex.h#L25-L30

Possibly, we should just ditch the `Rcomplex{` approach and do what {Rcpp} does here, building `Rcomplex` objects component-wise instead, WDYT @eddelbuettel?

**Comment by eddelbuettel** [comment]
I am all for borrowing smart approaches but can you `git blame` that code?  Also, glancing at the Rcpp file you seem to look at operator implementations whereas here we are fighting the constructor under newer clang.

**Comment by MichaelChirico** [comment]
> can you git blame that code

I did `git blame` the {Rcpp} code, it has "always" been like that:

https://github.com/RcppCore/Rcpp/commit/8b73d6a2e820eac65a0de8492bd453b196ed5866

I didn't see {Rcpp11} on GitHub ([hence](https://github.com/Rcpp11/Rcpp11/pull/232)), but now that I do I can see it was forked from {Rcpp}:

https://github.com/Rcpp11/Rcpp11/blame/2cedfb362ce067a72f0895c428235f5d622f4008/inst/include/Rcpp/complex.h
https://github.com/Rcpp11/Rcpp11/commit/f3ed04feedd19774232ee608fddccd6d43d06344

> you seem to look at operator implementations

Well, that's just what I happened to link. The focus is on `Rcomplex{...}`-style allocation, as opposed to `Rcomplex z; z.r= ...; z.i=...;`.
