### ISSUE TITLE
as.integer64 returns an error

### ISSUE THREAD

**Issue by restonslacker** [eddelbuettel/nanotime#15]
I'm not sure if this is exactly an _issue_ with `nanotime` but since `as.integer64.nanotime` is listed as a function in the help file for it, I wasn't expecting this behavior.

``` r
library(nanotime)
nt <- nanotime("2017-02-02T17:16:27.633531000+00:00")
as.integer64(nt)
#> Error in eval(expr, envir, enclos): could not find function "as.integer64"
suppressMessages(library(bit64))
as.integer64(nt)
#> integer64
#> [1] 1486055787633531000
```

Should I have to explicitly load `bit64` for this to work or is there a configuration issue with `nanotime`? Perhaps this is just a lack of understanding on my part.

**Comment by joshuaulrich** [comment]
`bit64` must be loaded and attached, otherwise the `as.integer64` generic isn't available.  If the generic isn't available, there's nothing to dispatch to the `as.integer64.nanotime` method.  That said, you can always call the generic directly: `bit64::as.integer(nt)`.

**Comment by restonslacker** [comment]
Given the fairly strong dependence of `nanotime` on `bit64` (at least, that's my impression from the 'Design' section of the help page), would it make sense to load and attach `bit64` by default?

**Comment by eddelbuettel** [comment]
Not sure.  `Depends` is sort-of frowned upon these days.  I would rather keep is 'loose' as it is now.

**Comment by joshuaulrich** [comment]
It's a thorny issue I've discussed with Achim Z before regarding xts and zoo.  To paraphrase his comments for this situation:

> `nanotime` could re-export the generic, but then any packages depending on `nanotime` must decide whether to register with `bit64::as.integer64` or `nanotime::as.integer64`. Or they have to fully export their S3 method so it would be found by either generic.

As Dirk said, using `Depends` is discouraged.  I think it would be especially so in this case, since it's not clear that users who want `nanotime` are also going to want every bit (pun intended) of `bit64` on their search path as well.

If you want to convert `nanotime` to `integer64`, I would ask: why?  Once you answer that, we might be able to have a discussion about adding functionality to `nanotime` to meet that need.

**Comment by eddelbuettel** [comment]
I pretty much feel the same way -- but this was eloquently put.   One really only wants explicit `integer64` for debugging.   

So I'd say leave as is ...

**Comment by eddelbuettel** [comment]
So ... would defining 

```
as.integer64 <- function(...) bit64::as.integer64(...)
```

as a free (and exported) function greatly upset the higher powers of generic functions? Seems to work:

```r
R> library(nanotime)     ## bit64 not loaded
R> as.integer64(nt)
integer64
[1] 1486055787633531000
R> 
```

and then

```r
R> suppressMessages(library(bit64))
R> as.integer64(nt)
[1] "2017-02-02T17:16:27.633531000+00:00"
R> class(as.integer64(nt))
[1] "nanotime"  "integer64"
R> bit64::as.integer64(nt)
[1] "2017-02-02T17:16:27.633531000+00:00"
R> nanotime:::as.integer64.nanotime(nt)
integer64
[1] 1486055787633531000
R> 
```

so it looks like worst case I may have to try clean up on class attribute stripping call.

**Comment by eddelbuettel** [comment]
Hm, I may have stumbled on the appropriate fix:

#### _With bit64_

```
edd@max:~/git/nanotime(feature/issue15)$ cat issue15with.R

library(nanotime)
suppressMessages(library(bit64))

nt <- nanotime("2017-02-02T17:16:27.633531000+00:00")
print(nt)
print(as.integer64(nt))

edd@max:~/git/nanotime(feature/issue15)$ r issue15with.R
[1] "2017-02-02T17:16:27.633531000+00:00"
integer64
[1] 1486055787633531000
edd@max:~/git/nanotime(feature/issue15)$ 
```

#### _Without bit64__

```
edd@max:~/git/nanotime(feature/issue15)$ cat issue15without.R

library(nanotime)

nt <- nanotime("2017-02-02T17:16:27.633531000+00:00")
print(nt)
print(as.integer64(nt))

edd@max:~/git/nanotime(feature/issue15)$ r issue15without.R
[1] "2017-02-02T17:16:27.633531000+00:00"
integer64
[1] 1486055787633531000
edd@max:~/git/nanotime(feature/issue15)$ 
```

That is what we wanted, in both cases.  Only change:  exporting `as.integer64` in NAMESPACE.

**Comment by eddelbuettel** [comment]
See #16, comments there welcome.  Seems to work, a fresh set of eyes may help.

**Comment by restonslacker** [comment]
To answer Josh's question on why I want to do the conversion, essentially it's serialization.  I'm interfacing with a system that wants time in microseconds from the epoch so this seemed like an easy way to fold that in.  

In a larger, not-my-immediate-problem, sense I feel like a function that shows up in the docs should just work or provide a better error message.
