### ISSUE TITLE
Example plots

### ISSUE THREAD

**Issue by McCompexpert** [eddelbuettel/nanotime#38]
Guys, could someone please post some simple plot examples on how to use nanotime to display nanosec timestamps on x axis. Thank you!

**Comment by lsilvest** [comment]
Have a look here: https://github/lsilvest/nanotime_ggplot

It addresses graphing with `data.table` indexed by `nanotime`, but you might be able to find what you need.

**Comment by eddelbuettel** [comment]
You have to do it by hand.  Here is a quick idea

```
library(nanotime)

set.seed(123)
x <- nanotime(Sys.time()) + cumsum(abs(runif(5, 0, 1e9)))
y <- rnorm(5)

xpt <- as.POSIXct(as.integer64(x)/1e9, origin="1970-01-01")
plot(xpt, y, axes=FALSE)
axis(2)
axis(1, at=xpt, labels=format(x))
box()
```

In essence, we convert to POSIXct, plot with that but then use `nanotime` formatting for the (hand-drawn) labels.  There is no plotting method for `nanotime` yet....

**Comment by McCompexpert** [comment]
Thanks a lot!
