### ISSUE TITLE
Error in callNextMethod() : error in evaluating a 'primitive' next method while doing rbind of data containing nanotime

### ISSUE THREAD

**Issue by wsrfad** [eddelbuettel/nanotime#39]
Error in callNextMethod() : error in evaluating a 'primitive' next method: Error in as.integer64(value) :argument \"value\" is missing, with no default
Calls: [<- -> [<-.integer64 -> as.integer64 [<- -> new -> initialize -> initialize -> callNextMethod

Why could I be facing this issue ?

**Comment by wsrfad** [comment]
Note : I am facing this issue on 1 machine & not on another machine. I have both machines at master version of nanotime; what could be the issue ?

**Comment by eddelbuettel** [comment]
Nobody can tell you unless you
- learn how to prepare a reproducible bug report
- stating versions used, OS used, ...

See maybe https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example or other tutorials.

**Comment by wsrfad** [comment]
I was already on my way to debug the code..But there may be a hunch produced by the developers of the code on when you see these kind of messages, or rather what kind of code paths suffer this. To have a reproducible bug, I will have to dig deeper into implementation of nanotime / callNextMethod, which I am already doing. Last, I raised an issue with deep analysis. But you always do not have time, a bit of idea may help you drill the exact issue faster. Anyways ..

**Comment by eddelbuettel** [comment]
It is a CRAN package. These have tests.  And they are tested.  See here:  https://cloud.r-project.org/web/checks/check_results_nanotime.html

So unless you prove something reproducible it most likely is "merely" an out of sync installation on your box.

**Comment by wsrfad** [comment]
Initial, yet useful info. Will get back with more. Meanwhile, if you have some info, so share

The machine where it repros, using the same code below, installs the dependencies 'bit', 'Rcpp', 'bit64', 'RcppCCTZ', 'zoo', while it does not do with the machine where it repros. (May be R version difference. I will verify).

Other messages, while installation
```
Creating a generic function for 'print' from package 'base' in package 'nanotime'
```
Error

```
error in evaluating a 'primitive' next method: Error: incompatible types (from symbol to double) in subassignment type fix"
Calls: rbind ... [<- -> new -> initialize -> initialize -> callNextMethod
```
Code
```
system("mkdir -p ~/R/library")
.libPaths( c( .libPaths(), "~/R/library") )
repo = "http://cran.us.r-project.org"
mylib = "~/R/library"
install.packages("nanotime", lib = mylib, repos = repo)
library("nanotime", lib.loc = .libPaths())
d = NULL
td = data.frame("time" = c("1", "2", "3"), "col" = c(1, 2, 3), stringsAsFactors = FALSE)
td$time = nanotime(as.integer64(td$time))
tmp = rbind(d, td)
```

**Comment by eddelbuettel** [comment]
The message is a just, a message.  It is _not_ an error.

Now your error code appears to be 

```r
d = NULL
td = data.frame("time" = c("1", "2", "3"), "col" = c(1, 2, 3), stringsAsFactors = FALSE)
td$time = nanotime(as.integer64(td$time))
tmp = rbind(d, td)
```

and I just shrug. You seem to be under the impression that we promised random concatenation starting from `NULL`.  Which works for me:

```
R> d <- NULL
R> td <- data.frame(t=nanotime(c(1, 2, 3)), col= 1:3, stringsAsFactors = FALSE)
R> td
                                    t col
1 1970-01-01T00:00:00.000000001+00:00   1
2 1970-01-01T00:00:00.000000002+00:00   2
3 1970-01-01T00:00:00.000000003+00:00   3
R> rbind(d,td)
                                    t col
1 1970-01-01T00:00:00.000000001+00:00   1
2 1970-01-01T00:00:00.000000002+00:00   2
3 1970-01-01T00:00:00.000000003+00:00   3
R> 
```

So maybe try the github version.  In general, I recommend sticking with data.table over data.frame.

**Comment by wsrfad** [comment]
I am using github version in both. I do not appreciate your lack of patience in closing this issue. Anyways, i  will get to the root of it ! 

While you say about rbind starting with NULL, it works with all other data !

**Comment by eddelbuettel** [comment]
Hm.  I also tried on a box where I am pretty sure it is the CRAN version that is installed, and it too worked.

**Comment by eddelbuettel** [comment]
Maybe you are not using the _current_ CRAN version. I can't tell -- your report has insufficient detail.

**Comment by wsrfad** [comment]
Now, try a repro:

Use R version 3.2.3
Install nanotime 
Rerun the same code..

**Comment by wsrfad** [comment]
d = NULL
td = data.frame("time" = c("1", "2", "3"), "col" = c(1, 2, 3), stringsAsFactors = FALSE)
#td$time = nanotime(as.integer64(td$time))
d = rbind(d, td)

If I comment your 'tested' nanotime, this does not give any error.

Now, this does repro ! I stand vindicated...

**Comment by wsrfad** [comment]
I know of one more nanotime issue even in release, but whatever happened is very disappointing. I chose not to raise it

**Comment by eddelbuettel** [comment]
> Use R version 3.2.3

I do this as a volunteer, and I do not have time to support three year old R versions.  That is your problem.  Try R 3.4.4 or R 3.5.1, things should work.  Good luck.

**Comment by eddelbuettel** [comment]
Your whole problem is, if I may guess, that you seem to insist on passing your integer64 arguments as characters, even though are numbers.  But whatever.

**Comment by eddelbuettel** [comment]
One last point:  You don't have a name.  You hide behind a pseudonym.  You have no repos.

We do this as a gift economy.  Most people who expect something for free (and of course also "immediately") at least try to give something back.  What have you done for us?   I grant you that your last bug report (which you then ignored for two weeks) was moderately helpful.  This exchange here however was a complete waste of time, yours and mine.

**Comment by wsrfad** [comment]
Thanks sir for maintaining. I respect that. But your tone could have been better / more encouraging for handling this issue. You could have said we do not support this version, or tell some workaround. Even do.call(rbind, lapply generated list) does not work. 

As regards '''passing your integer64 arguments as character''' is concerned, I did that as I was actually reading nanos time from a file, to read them with precision, I have to read them as character. So, I just used that code snippet. There is no perfect wise man in this world. We must respect each other and help each other become better. That would be real giving !

**Comment by eddelbuettel** [comment]
You could take a look at the existing documentation and try, say, look at the [README.md](https://github.com/eddelbuettel/nanotime) and just vary that:

```r
R> library(nanotime)
R> x <- nanotime("2018-01-02T03:04:05.006007008+00:00")
R> x
[1] "2018-01-02T03:04:05.006007008+00:00"
R> 
```

There is even `help(nanotime)`.  But why read when you can just try random crap and then waste my justifying it.
