### ISSUE TITLE
A finisher to an old issue

### ISSUE THREAD

**Issue by wsrfad** [eddelbuettel/nanotime#40]
https://github.com/eddelbuettel/nanotime/issues/39

I cannot help you ! 

Try this 

nanotime(1531830678123456789)

You will lose your precision !

Only to prove you need to convert to character !

**Comment by joshuaulrich** [comment]
This is related to [floating point precision](https://en.wikipedia.org/wiki/Double-precision_floating-point_format), and has nothing to do with nanotime.  [What Every Computer Scientist Should Know About Floating-Point Arithmetic](https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html) provides a lot of background for why this is an issue and how to work around it.

Your precision never existed, even before you called `nanotime()`:

```r
1531830678123456789
# [1] 1.531831e+18
sprintf("%f", 1531830678123456789)
# [1] "1531830678123456768.000000"
```

And this works:

```r
nanotime(bit64::as.integer64("1531830678123456789"))
[1] "2018-07-17T12:31:18.123456789+00:00"
```

**Comment by wsrfad** [comment]
Exactly ! That's why I was using time in character and then passing to nanotime. But eddelbuettel is hell bent on telling me that I do not do my homework ! Plz neither underestimate nor ridicule the feedback givers

**Comment by eddelbuettel** [comment]
@wsrfad One more time-wasting issue like this and I will [block you](https://help.github.com/articles/blocking-a-user-from-your-personal-account/).  This serves as a warning.  Your call.
