### ISSUE TITLE
create and export as.nanotime

### ISSUE THREAD

**Issue by jangorecki** [eddelbuettel/nanotime#47]
It might be sometimes useful to operate on arbitrary type objects. For example if `fread`'s `colClasses` arg will be supplied with `"nanotime"` type, then we could flexibly dispatch to arbitrary class by using
```r
convert = function(x, type) {
  as.call(c(as.name(paste("as", type, sep=".")), as.name("x")))
}
convert(x, type="nanotime")
#as.nanotime(x)
```
`as.*` functions are kind of standard in R.

**Comment by lsilvest** [comment]
If I understand correctly, the end goal would be something like this, with a conversion from `character` to `nanotime`?

~~~ R
fread("a_file_that_contains_nanotimes.csv", colClasses="nanotime")
~~~

**Comment by jangorecki** [comment]
fread was just an example of a function that could utilise `as.nanotime`.
source data type doesn't matter as long as there are methods to dispatch, `as.nanotime.character`, and most importantly `as.nanotime.deafult`.

**Comment by eddelbuettel** [comment]
For reasons I no longer remember I constructor was always just `nanotime()` so we could possibly simply alias and register.  We do register S3 methods for the other direction:

```r
S3method(as.Date,nanotime)
S3method(as.POSIXct,nanotime)
S3method(as.POSIXlt,nanotime)
S3method(as.data.frame,nanotime)
S3method(as.integer64,nanotime)
```

**Comment by lsilvest** [comment]
The reason I was asking for the end goal is that I'm not sure if there's a consensus that `as.to_type.from_type` be provided. The generic coercion function for an S4 class is `as` (by the way not yet implemented either for `nanotime`). So I don't think the `convert` function can expect full generality as is, especially for S4 classes. I'll try to dig into this a bit deeper...

**Comment by jangorecki** [comment]
@lsilvest regarding fread and `as.*` methods I mentioned, related point https://github.com/Rdatatable/data.table/commit/1de0399d5d58e500695dd04c7b8c4908ee456ce9#diff-8312ad0561ef661716b48d09478362f3R11
> `colClasses` now supports `'complex'`, `'raw'`, `'Date'`, `'POSIXct'`, and user-defined classes (so long as an `as.` method exists), [#491](https://github.com/Rdatatable/data.table/issues/491) [#1634](https://github.com/Rdatatable/data.table/issues/1634) [#2610]

**Comment by jangorecki** [comment]
example where `as.nanotime` could be helpful: https://github.com/Rdatatable/data.table/issues/4101

**Comment by eddelbuettel** [comment]
I am sorry but can you be more specific?  I read the #4101 link but it "didn't click".

**Comment by jangorecki** [comment]
Provided wrapper function calls `as.numeric` / `as.integer` / etc based on values in `colClasses` by calling `do.call(paste0("as.", colClasses[[i]]), ...)`, thus if user wants a column to be nanotime then `colClasses(time="nanotime", ...)` allows to automatically convert a column to nanotime.

**Comment by lsilvest** [comment]
Yes, I agree we should provide the `as.nanotime` methods. I think Dirk's suggestion to alias should work well. Furthermore, I think we should in parallel provide the `as` type coercion via `setAs` functions. This would provide generality in type conversion for `nanotime` whichever way a users chooses.
