### ISSUE TITLE
inherit integer64 class

### ISSUE THREAD

**Issue by jangorecki** [eddelbuettel/nanotime#48]
I wonder if it would make any problem if nanotime class would also inherits integer64?
It could be useful when dispatching, for example instead of following code:
```r
SWITCH(TYPEOF(x)) {
  case REALSXP: {
    if (inherits(x,"integer64") || inherits(x,"nanotime")) {
...
    } else { // numeric
...
    }
```
It would be sufficient to use:
```r
SWITCH(TYPEOF(x)) {
  case REALSXP: {
    if (inherits(x,"integer64")) {
...
    } else { // numeric
...
    }
```
In data.table we use similar logic for IDate class, which inherits from Date, thus we need to make single check for inheritance, not two.

**Comment by eddelbuettel** [comment]
It does in R:

```r
R> library(nanotime)
R> n <- nanotime(1)
R> n
[1] "1970-01-01T00:00:00.000000001+00:00"
R> class(n)
[1] "nanotime"
attr(,"package")
[1] "nanotime"
R> inherits(n, "nanotime")
[1] TRUE
R> inherits(n, "integer64")
[1] TRUE
R> 
```

We have no `src/` in this package _i.e._ we provide nothing at the C(++) level and do nothing there.

**Comment by jangorecki** [comment]
It somehow works in R but not in R C API which probably operates as loop over character vector from `class(.)`, and that does not return `"integer64"`. If there is an intent to inherit from integer64 then why not to add it to class?

**Comment by eddelbuettel** [comment]
I have no idea what you are trying to say, other than I understand what pony you want.  If you have a way to implement it, go for it in a PR.  Else this will get closed.  It is an R-only package.

**Comment by eddelbuettel** [comment]
We could of course be missing a simple S3/S4 interaction thingie. I have no idea.  But the package works otherwise so I have limited interest in going wild here.

**Comment by jangorecki** [comment]
Yes, it is the issue with S4 class, as explained in `?class` it will return scalar character for S4. We would need to change `inherits` calls to some S4-specific calls in such case.
