### ISSUE TITLE
Comparing nanotime with a character

### ISSUE THREAD

**Issue by statquant** [eddelbuettel/nanotime#52]
Hello, I am using nanotime in conjuction with `data.table` a lot now and I would have thought being able to compare nanotime with character would be good syntactic suggar.
I mean

```
options(nanotimeFormat = "%Y-%m-%dT%H:%M:%E9S")
nanotime("2018-12-28T16:34:59.649943448") > "2018-12-28T16:34:59.000000000"
[1] NA
```
would be equivalent to
```
options(nanotimeFormat = "%Y-%m-%dT%H:%M:%E9S")
nanotime("2018-12-28T16:34:59.649943448") > nanotime("2018-12-28T16:34:59.000000000")
[1] TRUE
```
I `data.table` this get very appreciable I think and this links well with https://github.com/eddelbuettel/nanotime/issues/51
I am happy to try to do a PR but wanted to check first that I am not missing something and/or/hence the PR would be rejected

**Comment by eddelbuettel** [comment]
Well, first off your example doen't work (without the timezone argument expected by the parser).  

Second, a naive attempt of defining `>` and `<` did not work.  @lsilvest may know more as he is deeper into the s4 weeds than I am.

**Comment by eddelbuettel** [comment]
This seems to work:

modified   R/nanotime.R
@@ -398,6 +398,14 @@ setMethod("Arith", c("ANY", "nanotime"),
               stop("operation not defined for \"nanotime\" objects")    ## #nocov
           })
 
```r
+##' @rdname nanotime
+##' @export
+setMethod("Compare", c("nanotime", "character"),
+          function(e1, e2) {
+              ne2 <- nanotime(e2)
+              callNextMethod(e1, ne2)
+          })
+
 ##' @rdname nanotime
 ##' @export
 setMethod("Compare", c("nanotime", "ANY"),
```

Thoughts, @lsilvest ?

**Comment by lsilvest** [comment]
That should work, and also it would make sense I think to define it for `c("character", "nanotime"`.

**Comment by eddelbuettel** [comment]
Done in 75eec4c. Appears to upset one unit test which I should have checked earlier already.

Example:  

```r
R> library(nanotime)
R> "2018-12-28T16:34:59.649943448+00:00" < nanotime("2018-12-28T16:34:59.000000000+00:00")
[1] FALSE
R> "2018-12-28T16:34:59.649943448+00:00" > nanotime("2018-12-28T16:34:59.000000000+00:00")
[1] TRUE
R> 
```

Good S4 benefit to be able to do it both ways.

**Comment by statquant** [comment]
> Well, first off your example doen't work (without the timezone argument expected by the parser).

That was in my .Rprofile sorry, edited the initial question
Will use the lattest dev, thanks for the prompt answer

**Comment by eddelbuettel** [comment]
Ok, this should be taken care of in #54.
