### ISSUE TITLE
Comparing nanotime with a POSIXct

### ISSUE THREAD

**Issue by statquant** [eddelbuettel/nanotime#57]
Hello, 
in addition to https://github.com/eddelbuettel/nanotime/issues/52 can I suggest to add comparator for POSIXct ?

> nanotime(Sys.time()) > (Sys.time() - 10)
> [1] FALSE
> Warning messages:
> 1: In if (class(e2) == "nanotime") { :
>   the condition has length > 1 and only the first element will be used
> 2: In eval(call, callEnv) :
>   Incompatible methods (">.integer64", "Ops.POSIXt") for ">"

**Comment by eddelbuettel** [comment]
Would you mind mocking or testing it?  Given that POSIXct is a hybrid S3 class, I am not sure we can from S4.  (We might, I just don't know ...)

**Comment by statquant** [comment]
Ok, will come back with a PR if I can manage, S3/S4 concepts are new to me.
Thanks

**Comment by lsilvest** [comment]
This works when defining the appropriate methods. I've added these comparisons in the `feature/temporal_types` branch and they will be available soon when it is merged in `master`.

**Comment by statquant** [comment]
Thank you, I was hoping to be of some help but never got to try.
Many thank for all the hard for for the community
