### ISSUE TITLE
Define a shorter notation to get `nanotime-nanoival` subset index

### ISSUE THREAD

**Issue by lsilvest** [eddelbuettel/nanotime#59]
This would allow an efficient subsetting of a `data.table` time-series with a `nanotime` column with more clarity than using `intersect.idx`.

Given a `data.table` _dt_ with a `nanotime` index _idx_ and a vector of `nanoival` _ni_, we can then write:

```r
dt[idx %in% ni]
```

and get a subset of a _dt_.

**Comment by eddelbuettel** [comment]
Nice. I presume this assumes regularly gridded observations so that equality (on int64 values) holds?

**Comment by lsilvest** [comment]
`%in%-nanotime-nanotime` is already defined because of `integer64` inheritance and you are right that it's direct equality.

For `%in%-nanotime-nanoival`, it's not equality, but it's about which `nanotime` observations are included in the interval vector. 

What's cool with a `nanoival` vector is that it allows for pretty complex subsettting. For example subsetting price time-series from different exchanges in different timezones to the times where the exchanges' hours overlap. For this, one can construct a `nanoival` vector from the calendar for each exchange. Then one uses `intersect` on these `nanoival` vectors in order to get the final intervals that define the overlapping. Finally, with the `%in%` operator one can efficiently subset any time-series to the overlapping times.

**Comment by eddelbuettel** [comment]
That would totally rock!  "So far" best practices I knew involved some `data.table` juggling.  A new operator would be awesome!
