### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/nanotime#6]
Maybe a little tricky to get at `std::chrono` without CCTZ and Rcpp but doable. Would forgo the formatting, parsing, TZ help. 

At a strict minimum someone driven-enough could extend Simon's [fasttime](https://github.com/s-u/fasttime) to return two doubles (in UTC time) as we do -- which would cover parsing.  Formating could be done as a kludge with `strftime` and `sprintf` as we already do for fractional seconds.  Likely brittle though.

Maybe someone should just port [CCTZ](https://github.com/google/cctz) to Windows?  Or maybe just build it and have it skip TZ operations for lack of zoneinfo and still parse / format at UTC?

**Comment by dcdillon** [comment]
We solved this, no?

**Comment by eddelbuettel** [comment]
Yes, pending release.
