### ISSUE TITLE
subsetting with NA incorrect

### ISSUE THREAD

**Issue by lsilvest** [eddelbuettel/nanotime#66]
``` R
> as.nanotime(1)[NA]
[1] 2262-02-18T20:47:17.227407266+00:00
```
For `nanotime` that's because `integer64` is not handling NA correctly:

``` R
> as.integer64(1)[NA]
integer64
[1] 9218868437227407266
```

As opposed to:

``` R
> as.integer(1)[NA]
[1] NA
```

So for `nanotime` and `nanoduration` we could ask Jens or go ahead and implement our own subsetting functions.

But unfortunately we are also handling our non-integer64-based types incorrecty:

``` R
> as.nanoival("+2012-01-01 UTC -> 2012-02-02 UTC-")[NA]
[1] +2116-01-25T22:23:38.613703633+00:00 -> 2116-01-25T22:23:38.613703633+00:00+
> as.nanoperiod("1d")[NA]
[1] 1954m2146435072d/2560796:47:17.227_407_266
```

**Comment by eddelbuettel** [comment]
Uggh. Not pretty. To change it, additional logic is needed in the `[` functions?

**Comment by lsilvest** [comment]
Yes. If we do it at R level it will mean additional passes, so probably better to do it at C level.
