### ISSUE TITLE
Timestamp parsing error

### ISSUE THREAD

**Issue by Famguy** [eddelbuettel/nanotime#78]
Hi there!

I am facing the following error while using nanotime with my timestamps.
R version: 3.2.3
Platform: Ubuntu 16.04.6 LTS (x86_64)

```
> nanotime("2020-08-20 03:45:30.511400598", format ="%Y-%m-%d %H:%M:%E9S",  tz ="GMT")
[1] "20200820 03:45:30.511400598"

> nanotime("20200820 03:45:30.511400598", format ="%Y%m%d %H:%M:%E9S",  tz ="GMT")
Error in RcppCCTZ::parseDouble(x, fmt = format, tz = tz) : 
  Parse error on 20200820 03:45:30.511400598

```

As you see, it works with date in %Y-%m-%d format, but doesn't work for %Y%m%d. Is there any issue in the way I'm calling nanotime?

Thanks in advance!

**Comment by eddelbuettel** [comment]
Hi @Famguy 

So as mentioned, `nanotime` relies on `RcppCCTZ` which wraps `CCTZ`.  And I thought I had seen earlier issues to I just went back and checked.  And indeed:

- https://github.com/google/cctz/issues/137 recommends %E4Y for a four digit year (will test in a second)
- https://github.com/google/cctz/issues/79 same
- https://github.com/google/cctz/issues/25 same, also mentions %E4Y%M%D

all discuss it.  We will make sure to fold some example use cases of `%E4Y` into our documentation.
