### ISSUE TITLE
Convenience constructor for seconds + nanoseconds

### ISSUE THREAD

**Issue by dcdillon** [eddelbuettel/nanotime#8]
Due to R's data type restrictions (and the usual implementation of `struct timespec`) it would be nice to have a shortcut way to instantiate a `nanotime` from two integer values: seconds since epoch, nanoseconds since last second).

Not critical, just convenience.

**Comment by eddelbuettel** [comment]
Do you mean at the R or at the C++ level?  In R, seconds since epoch is the usual conversion from POSIXct:

```r
R> format(nanotime(now))
[1] "2017-01-11T17:59:03.210716+00:00"
R> format(nanotime(as.numeric(now)*1e9))
[1] "2017-01-11T17:59:03.210716672+00:00"
R> 
```

The two are the same (relative to rounding error) as nanotime has nanoseconds since epoch \approx (fractional) seconds since epoch \times 1e9

Nanoseconds since last second sounds weird.  Just instantiate _that_ last second and add to it:

```r
R> format(nanotime(now)  + 42)    # 42 nsec later
[1] "2017-01-11T17:59:03.210716042+00:00"
R> 
```

**Comment by dcdillon** [comment]
Like I said, just convenience for times coming from other sources.  `struct timespec` has exactly that:  seconds since epoch and nanoseconds since last second.

**Comment by eddelbuettel** [comment]
Right. But isn't what [RcppCCTZ does with darseDatetime](https://github.com/eddelbuettel/rcppcctz/blob/master/src/utilities.cpp#L253-L282) (returning two values) which we then use [here](https://github.com/eddelbuettel/nanotime/blob/master/R/nanotime.R#L96-L101) in a somewhat ill-named helper.

**Comment by eddelbuettel** [comment]
Here is a minimal answers.  Start with `sourceCpp()` on this to get `struct timeres` to R:

```c++

#include <Rcpp.h>

// [[Rcpp::plugins(cpp11)]]

// [[Rcpp::export]]
Rcpp::NumericMatrix hiresNow() {
  struct timespec ts;
  timespec_get(&ts, TIME_UTC);
  Rcpp::NumericMatrix M(1,2);
  M(0,0) = ts.tv_sec;
  M(0,1) = ts.tv_nsec;
  return M;
}
```

This basically just wraps access to `struct timeres` into a function returning the `Matrix` representation I already needed anyway.

Then:

```r
R> library(Rcpp)
R> sourceCpp("/tmp/danCtor.cpp")
R> M <- hiresNow(); now <- Sys.time()
R> M
           [,1]      [,2]
[1,] 1484183403 196793033
R> library(nanotime)
R> nanotime:::nanotime.matrix(M)
integer64
[1] 1484183403196793033
R> format(nanotime:::nanotime.matrix(M))    # at UTC
[1] "2017-01-12T01:10:03.196793033+00:00"
R> now                                                           # local POSIXct
[1] "2017-01-11 19:10:03.207415 CST"         
R> format(now, tz="UTC")                             # POSIXct at UTC
[1] "2017-01-12 01:10:03.207415"
R> 
```

and the difference is the difference in the time in `M <- hiresNow(); now <- Sys.time()` which appears to be 10 msec or so.  Sounds about right.

So you just need to write yourself a convenience wrapper for `nanotime:::nanotime.matrix()`.
