### ISSUE TITLE
Could you implement comparaison on nanoduration and Character

### ISSUE THREAD

**Issue by statquant** [eddelbuettel/nanotime#87]
Hello @eddelbuettel and @lsilvest 
Would you consider implementing comparaison for nanoduration as you did for nanotime ?

```
library(nanotime)
options(nanotimeFormat = "%Y-%m-%dT%H:%M:%E9S")
# this is a nanoduration
as.nanotime("2020-11-30T16:11:39.860999936") - as.nanotime("2020-11-30T16:11:38.960999936")
[1] 00:00:00.900
# you can compare nanotime to Character
as.nanotime("2020-11-30T16:11:39.860999936") < "2020-11-30T16:11:38.960999936"
[1] FALSE
# but you cannot compare nanoduration to Character
(as.nanotime("2020-11-30T16:11:39.860999936") - as.nanotime("2020-11-30T16:11:38.960999936")) < "00:00:00.999"
[1] NA
# the expected output would be the same as
(as.nanotime("2020-11-30T16:11:39.860999936") - as.nanotime("2020-11-30T16:11:38.960999936")) < as.nanoduration("00:00:00.999")
[1] TRUE
attr(,".S3Class")
[1] "integer64"
```

I think that would be very useful, I would personally use nanoduration as replacement of hms
Kind regards

PS: ran in `R 4.0.3 --vanilla`

**Comment by eddelbuettel** [comment]
We might (as always) consider careful pull requests.

**Comment by eddelbuettel** [comment]
![image](https://user-images.githubusercontent.com/673121/100797460-c75aa300-33e7-11eb-9e12-2acc5fd0fb51.png)

**Comment by statquant** [comment]
This is totally off topic, my request was totally cordial and could not be considered as a demand by any standard.
I join the rest of this twit that you "forgot"

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Related: if something is missing, don&#39;t walk away without asking about it. Features/docs can be added if you draw attention to them. They may have simply been overlooked before, or nobody cared enough yet. If you care enough, you can make it happen.</p>&mdash; Howard Chu (@hyc_symas) <a href="https://twitter.com/hyc_symas/status/1333868283896991745?ref_src=twsrc%5Etfw">December 1, 2020</a></blockquote> 

 I was going to reply that I will give a go to a PR given I could use nanotime as an example, I guess that both our losses

**Comment by eddelbuettel** [comment]
You closed the PR without comment and walked away.  If you have a design spec for a PR feel free to propose it.  It already said we're open to it.  Otherwise let's end it here to not waste your precious time.  Or ours.
