### ISSUE TITLE
Duration since yesterday's midnight in some timezone

### ISSUE THREAD

**Issue by statquant** [eddelbuettel/nanotime#89]
Hello `nanotime` authors.
When using `nanotime` in conjunction with `data.table` one often needs to extract the time of day portion of a `nanotime` to compute quantities across dates (say how many entries did a process record on average, per date, between 08:00 and 09:00 in 2020 in some TZ).
I understand that `nanoduration` is not meant to be a time class but it is fairly close. 

How about a function that would return the duration of a `nanotime` since previous date midnight (hence expressed in a given timezone) ?
Going back to string is pretty costly and could likely be instant

```
library(nanotime)         
library(data.table)
options(nanotimeFormat = "%Y-%m-%dD%H:%M:%E3S%z")
options(nanotimeTz = "Europe/Paris")
set.seed(1L)
start_ts <- nanotime("2020-08-03 UTC")                                                                                
one_hour <- 3600e9                                                                                                     
N <- 1e7                                                                                                               
DT <- data.table(ts = start_ts + runif(N, max = 12 * one_hour))                                                        
# takes                                                                                                                
# - 3 secs on my laptop for "%H:00:00"                                                                                 
# - 9 secs on my laptop for "%H:%M:%E3S"                                                                               
system.time({                                                                                                          
    DT[, time_str := format(ts, format = "%H:%M:%E3S")]                                                                
})                                                                                                                     
# pretty much instantaneous but is the offset since midnight in UTC                                                                                        
system.time({                                                                                                          
    DT[, time_nd := as.nanoduration(as.integer64(ts) %% 86400e9)]                                                      
})                                                                                                                     
```

Is there already an efficient way to do this that I am missing ?
If not and if you do not have strong opinion against it I could provide a PR for this.

**Comment by lsilvest** [comment]
You should be able to get to what you want by using `nano_floor` with a `nanoperiod` and a time zone, and then taking the difference, but the current implementation requires the vector on which `nano_floor` operates to be sorted:

``` R
setkey(DT, ts)
system.time({ 
    DT[, time_nd_floor := ts - nano_floor(ts, as.nanoperiod("1d"), tz="Europe/Paris")]
})

user  system elapsed 
0.148   0.064   0.211 
```

If the sorted requirement is not workable for you, it might make sense to extend `nano_floor` to be able to handle non-sorted vectors (necessarily less efficiently) rather than implementing an ad hoc function.

**Comment by eddelbuettel** [comment]
I think I have also done things similar to this by taking a (formatted) "cutoff" point, converting it to the underlying numeric representation and from there on just taking difference at the numeric level.  But hey I may have misunderstood the task...

**Comment by statquant** [comment]
Hello, thanks for the prompt answers
@lsilvest thanks for your solution, the sorting is no issue in my use-case. Although `nano_floor` is described in the vignette it didn't clicked when reading it.
@eddelbuettel  I am not sure I see what you mean, I might be missing yet another trivial thing.

**Comment by statquant** [comment]
closing now, thanks
