### ISSUE TITLE
Include trailing 0 (always 9 digits) for easier scanning 

### ISSUE THREAD

**Issue by mattdowle** [eddelbuettel/nanotime#9]
For example, this looks like 7 nanoseconds on first glance : 

```R
> format(nanotime(cooked$rdsent[1]))
[1] "2016-09-28T15:30:00.00000007+00:00"
```

but you have to look closely to realize there's just 8 subsecond digits there.  So it's actually 70 nanoseconds.

Current behaviour : 

> format(nanotime(as.integer64("1475076600000000070")))
[1] "2016-09-28T15:30:00.00000007+00:00"
> format(nanotime(as.integer64("1475076600000000071")))
[1] "2016-09-28T15:30:00.000000071+00:00"

Desired behaviour : 

> format(nanotime(as.integer64("1475076600000000070")))
[1] "2016-09-28T15:30:00.000000070+00:00"
> format(nanotime(as.integer64("1475076600000000071")))
[1] "2016-09-28T15:30:00.000000071+00:00"

**Comment by eddelbuettel** [comment]
Not me but the underlying [CCTZ](https://github.com/google/cctz) C++ library so ...

**Comment by eddelbuettel** [comment]
[This line](https://github.com/google/cctz/blob/master/src/time_zone_format.cc#L251) in the corresponding [CCTZ](https://github.com/google/cctz) source file is your friend.  Witness:

```
R> library(nanotime)
R> matt <- nanotime(70)
R> format(matt)
[1] "1970-01-01T00:00:00.00000007+00:00"
R> options("nanotimeFormat"="%Y-%m-%d %H:%M:%E9S%Ez")  # force nine digits
R> format(matt)
[1] "1970-01-01 00:00:00.000000070+00:00"
R> 
```

**Comment by eddelbuettel** [comment]
I made the change [in this branch](https://github.com/eddelbuettel/nanotime/tree/feature/better_print) which also fixes the printing issue.  Try that.

**Comment by eddelbuettel** [comment]
Thanks again for this, I folded it into master now.
