### ISSUE TITLE
Add to awesome-vctrs?

### ISSUE THREAD

**Issue by krlmlr** [eddelbuettel/nanotime#98]
This package looks like a good fit for https://github.com/krlmlr/awesome-vctrs#date-and-time, a list of vector classes I curate. Would you like to add it to that list? Happy to review a pull request.

**Comment by eddelbuettel** [comment]
We're good here.  No need for an issue AFAICT.  If someone (you?) wants to write about this package (after apparently ignoring this on-CRAN package for half a decade) that is fine but not really our concern.
